// checksum_config_full.h — consolidated per-ID CRC flags 
#pragma once
#include <stdint.h>

// checksum_config_full.h — consolidated per-ID CRC flags 
#pragma once
#include <stdint.h>
#include "checksum.h"  // ensures SeedMode, MaskMode, OrderMode enums are visible
#include "checksum_types.h"

// #define CHECKSUM_PROG_ENTRIES_COUNT (sizeof(CHECKSUM_PROG_ENTRIES)/sizeof(CHECKSUM_PROG_ENTRIES[0]))



// ID 0x40 — best_ratio=1.000000
#define CHECKSUMCFG_40_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_40_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_40_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_40_EXTRA       EXTRA_NONE

// ID 0x41 — best_ratio=1.000000
#define CHECKSUMCFG_41_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_41_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_41_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_41_EXTRA       EXTRA_NONE

// ID 0x86 — best_ratio=1.000000
#define CHECKSUMCFG_86_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_86_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_86_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_86_EXTRA       EXTRA_NONE

// ID 0x8A — best_ratio=1.000000
#define CHECKSUMCFG_8A_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_8A_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_8A_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_8A_EXTRA       EXTRA_NONE

// ID 0x9F — best_ratio=1.000000
#define CHECKSUMCFG_9F_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_9F_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_9F_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_9F_EXTRA       EXTRA_NONE

// ID 0xA7 — best_ratio=1.000000
#define CHECKSUMCFG_A7_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_A7_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_A7_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_A7_EXTRA       EXTRA_NONE

// ID 0xA8 — best_ratio=1.000000
#define CHECKSUMCFG_A8_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_A8_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_A8_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_A8_EXTRA       EXTRA_NONE

// ID 0xAD — best_ratio=1.000000
#define CHECKSUMCFG_AD_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_AD_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_AD_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_AD_EXTRA       EXTRA_NONE

// ID 0xB1 — best_ratio=1.000000
#define CHECKSUMCFG_B1_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_B1_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_B1_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_B1_EXTRA       EXTRA_NONE

// ID 0xB2 — best_ratio=1.000000
#define CHECKSUMCFG_B2_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_B2_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_B2_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_B2_EXTRA       EXTRA_NONE

// ID 0xFD — best_ratio=1.000000
#define CHECKSUMCFG_FD_SEED_MODE   SEED_BRUTE_TRACKED
#define CHECKSUMCFG_FD_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_FD_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_FD_EXTRA       EXTRA_NONE

// ID 0x101 — best_ratio=1.000000
#define CHECKSUMCFG_101_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_101_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_101_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_101_EXTRA       EXTRA_NONE

// ID 0x104 — best_ratio=1.000000
#define CHECKSUMCFG_104_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_104_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_104_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_104_EXTRA       EXTRA_NONE

// ID 0x106 — best_ratio=1.000000
#define CHECKSUMCFG_106_SEED_MODE   SEED_FIXED_FF
#define CHECKSUMCFG_106_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_106_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_106_EXTRA       EXTRA_NONE

// ID 0x116 — best_ratio=1.000000
#define CHECKSUMCFG_116_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_116_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_116_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_116_EXTRA       EXTRA_NONE

// ID 0x117 — best_ratio=1.000000
#define CHECKSUMCFG_117_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_117_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_117_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_117_EXTRA       EXTRA_NONE

// ID 0x118 — best_ratio=1.000000
#define CHECKSUMCFG_118_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_118_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_118_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_118_EXTRA       EXTRA_NONE

// ID 0x11D — best_ratio=1.000000
#define CHECKSUMCFG_11D_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_11D_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_11D_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_11D_EXTRA       EXTRA_NONE

// ID 0x11E — best_ratio=1.000000
#define CHECKSUMCFG_11E_SEED_MODE   SEED_BRUTE_TRACKED
#define CHECKSUMCFG_11E_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_11E_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_11E_EXTRA       EXTRA_NONE

// ID 0x120 — best_ratio=1.000000
#define CHECKSUMCFG_120_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_120_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_120_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_120_EXTRA       EXTRA_NONE

// ID 0x121 — best_ratio=1.000000
#define CHECKSUMCFG_121_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_121_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_121_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_121_EXTRA       EXTRA_NONE

// ID 0x126 — best_ratio=1.000000
#define CHECKSUMCFG_126_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_126_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_126_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_126_EXTRA       EXTRA_NONE

// ID 0x12E — best_ratio=1.000000
#define CHECKSUMCFG_12E_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_12E_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_12E_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_12E_EXTRA       EXTRA_NONE

// ID 0x130 — best_ratio=1.000000
#define CHECKSUMCFG_130_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_130_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_130_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_130_EXTRA       EXTRA_NONE

// ID 0x134 — best_ratio=1.000000
#define CHECKSUMCFG_134_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_134_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_134_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_134_EXTRA       EXTRA_NONE

// ID 0x135 — best_ratio=1.000000
#define CHECKSUMCFG_135_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_135_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_135_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_135_EXTRA       EXTRA_NONE

// ID 0x18C — best_ratio=1.000000
#define CHECKSUMCFG_18C_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_18C_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_18C_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_18C_EXTRA       EXTRA_NONE

// ID 0x1A2 — best_ratio=1.000000
#define CHECKSUMCFG_1A2_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_1A2_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_1A2_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_1A2_EXTRA       EXTRA_NONE

// ID 0x1AB — best_ratio=1.000000
#define CHECKSUMCFG_1AB_SEED_MODE   SEED_CARRY_FORWARD
#define CHECKSUMCFG_1AB_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_1AB_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_1AB_EXTRA       EXTRA_NONE

// ID 0x2B7 — best_ratio=1.000000
#define CHECKSUMCFG_2B7_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_2B7_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_2B7_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_2B7_EXTRA       EXTRA_NONE

// ID 0x30B — best_ratio=1.000000
#define CHECKSUMCFG_30B_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_30B_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_30B_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_30B_EXTRA       EXTRA_NONE

// ID 0x30D — best_ratio=1.000000
#define CHECKSUMCFG_30D_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_30D_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_30D_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_30D_EXTRA       EXTRA_NONE

// ID 0x31B — best_ratio=1.000000
#define CHECKSUMCFG_31B_SEED_MODE   SEED_CARRY_FORWARD
#define CHECKSUMCFG_31B_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_31B_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_31B_EXTRA       EXTRA_NONE

// ID 0x32A — best_ratio=1.000000
#define CHECKSUMCFG_32A_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_32A_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_32A_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_32A_EXTRA       EXTRA_NONE

// ID 0x365 — best_ratio=1.000000
#define CHECKSUMCFG_365_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_365_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_365_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_365_EXTRA       EXTRA_NONE

// ID 0x366 — best_ratio=1.000000
#define CHECKSUMCFG_366_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_366_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_366_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_366_EXTRA       EXTRA_NONE

// ID 0x380 — best_ratio=1.000000
#define CHECKSUMCFG_380_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_380_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_380_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_380_EXTRA       EXTRA_NONE

// ID 0x381 — best_ratio=1.000000
#define CHECKSUMCFG_381_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_381_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_381_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_381_EXTRA       EXTRA_NONE

// ID 0x382 — best_ratio=1.000000
#define CHECKSUMCFG_382_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_382_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_382_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_382_EXTRA       EXTRA_NONE

// ID 0x385 — best_ratio=1.000000
#define CHECKSUMCFG_385_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_385_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_385_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_385_EXTRA       EXTRA_NONE

// ID 0x391 — best_ratio=1.000000
#define CHECKSUMCFG_391_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_391_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_391_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_391_EXTRA       EXTRA_NONE

// ID 0x392 — best_ratio=1.000000
#define CHECKSUMCFG_392_SEED_MODE   SEED_UNKNOWN
#define CHECKSUMCFG_392_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_392_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_392_EXTRA       EXTRA_NONE

// ID 0x395 — best_ratio=1.000000
#define CHECKSUMCFG_395_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_395_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_395_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_395_EXTRA       EXTRA_NONE

// ID 0x3BE — best_ratio=1.000000
#define CHECKSUMCFG_3BE_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_3BE_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_3BE_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_3BE_EXTRA       EXTRA_NONE

// ID 0x3C0 — best_ratio=1.000000
#define CHECKSUMCFG_3C0_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_3C0_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_3C0_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_3C0_EXTRA       EXTRA_NONE

// ID 0x3C8 — best_ratio=1.000000
#define CHECKSUMCFG_3C8_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_3C8_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_3C8_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_3C8_EXTRA       EXTRA_NONE

// ID 0x3DB — best_ratio=1.000000
#define CHECKSUMCFG_3DB_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_3DB_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_3DB_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_3DB_EXTRA       EXTRA_NONE

// ID 0x3E5 — best_ratio=1.000000
#define CHECKSUMCFG_3E5_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_3E5_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_3E5_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_3E5_EXTRA       EXTRA_NONE

// ID 0x3E8 — best_ratio=1.000000
#define CHECKSUMCFG_3E8_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_3E8_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_3E8_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_3E8_EXTRA       EXTRA_NONE

// ID 0x3EC — best_ratio=1.000000
#define CHECKSUMCFG_3EC_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_3EC_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_3EC_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_3EC_EXTRA       EXTRA_NONE

// ID 0x3FE — best_ratio=1.000000
#define CHECKSUMCFG_3FE_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_3FE_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_3FE_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_3FE_EXTRA       EXTRA_NONE

// ID 0x497 — best_ratio=1.000000
#define CHECKSUMCFG_497_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_497_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_497_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_497_EXTRA       EXTRA_NONE

// ID 0x520 — best_ratio=1.000000
#define CHECKSUMCFG_520_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_520_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_520_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_520_EXTRA       EXTRA_NONE

// ID 0x54B — best_ratio=1.000000
#define CHECKSUMCFG_54B_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_54B_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_54B_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_54B_EXTRA       EXTRA_NONE

// ID 0x584 — best_ratio=1.000000
#define CHECKSUMCFG_584_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_584_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_584_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_584_EXTRA       EXTRA_NONE

// ID 0x585 — best_ratio=1.000000
#define CHECKSUMCFG_585_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_585_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_585_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_585_EXTRA       EXTRA_NONE

// ID 0x5BE — best_ratio=1.000000
#define CHECKSUMCFG_5BE_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_5BE_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_5BE_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_5BE_EXTRA       EXTRA_NONE

// ID 0x5F0 — best_ratio=1.000000
#define CHECKSUMCFG_5F0_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_5F0_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_5F0_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_5F0_EXTRA       EXTRA_NONE

// ID 0x640 — best_ratio=1.000000
#define CHECKSUMCFG_640_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_640_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_640_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_640_EXTRA       EXTRA_NONE

// ID 0x641 — best_ratio=1.000000
#define CHECKSUMCFG_641_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_641_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_641_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_641_EXTRA       EXTRA_NONE

// ID 0x64A — best_ratio=1.000000
#define CHECKSUMCFG_64A_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_64A_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_64A_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_64A_EXTRA       EXTRA_NONE

// ID 0x65D — best_ratio=1.000000
#define CHECKSUMCFG_65D_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_65D_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_65D_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_65D_EXTRA       EXTRA_NONE

// ID 0x65F — best_ratio=1.000000
#define CHECKSUMCFG_65F_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_65F_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_65F_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_65F_EXTRA       EXTRA_NONE

// ID 0x668 — best_ratio=1.000000
#define CHECKSUMCFG_668_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_668_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_668_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_668_EXTRA       EXTRA_NONE

// ID 0x670 — best_ratio=1.000000
#define CHECKSUMCFG_670_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_670_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_670_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_670_EXTRA       EXTRA_NONE

// ID 0x6AE — best_ratio=1.000000
#define CHECKSUMCFG_6AE_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_6AE_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_6AE_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_6AE_EXTRA       EXTRA_NONE

// ID 0x6B2 — best_ratio=1.000000
#define CHECKSUMCFG_6B2_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_6B2_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_6B2_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_6B2_EXTRA       EXTRA_NONE

// ID 0x6B4 — best_ratio=1.000000
#define CHECKSUMCFG_6B4_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_6B4_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_6B4_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_6B4_EXTRA       EXTRA_NONE

// ID 0x6B7 — best_ratio=1.000000
#define CHECKSUMCFG_6B7_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_6B7_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_6B7_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_6B7_EXTRA       EXTRA_NONE

// ID 0x6B8 — best_ratio=1.000000
#define CHECKSUMCFG_6B8_SEED_MODE   SEED_FIXED_00
#define CHECKSUMCFG_6B8_MASK_MODE   MASK_NONE
#define CHECKSUMCFG_6B8_ORDER       ORDER_NORMAL
#define CHECKSUMCFG_6B8_EXTRA       EXTRA_NONE
