#pragma once
#include <stdint.h>
#include "checksum_config_full.h"

// -----------------------------------------------------------------------------
// Per-ID configuration table for Teensy runtime checksum logic
// -----------------------------------------------------------------------------

typedef struct {
    uint32_t id;
    uint8_t  seed;
    uint8_t  mask;
    uint8_t  order;
    uint8_t  extra;
} PerIdCfg;

// -----------------------------------------------------------------------------
// Table: PER_ID_CFG_TABLE
// Each entry corresponds to one CAN ID from checksum_config_full.h
// -----------------------------------------------------------------------------

static const PerIdCfg PER_ID_CFG_TABLE[] = {
    { 0x040, CHECKSUMCFG_40_SEED_MODE,  CHECKSUMCFG_40_MASK_MODE,  CHECKSUMCFG_40_ORDER,  CHECKSUMCFG_40_EXTRA },
    { 0x041, CHECKSUMCFG_41_SEED_MODE,  CHECKSUMCFG_41_MASK_MODE,  CHECKSUMCFG_41_ORDER,  CHECKSUMCFG_41_EXTRA },
    { 0x086, CHECKSUMCFG_86_SEED_MODE,  CHECKSUMCFG_86_MASK_MODE,  CHECKSUMCFG_86_ORDER,  CHECKSUMCFG_86_EXTRA },
    { 0x08A, CHECKSUMCFG_8A_SEED_MODE,  CHECKSUMCFG_8A_MASK_MODE,  CHECKSUMCFG_8A_ORDER,  CHECKSUMCFG_8A_EXTRA },
    { 0x09F, CHECKSUMCFG_9F_SEED_MODE,  CHECKSUMCFG_9F_MASK_MODE,  CHECKSUMCFG_9F_ORDER,  CHECKSUMCFG_9F_EXTRA },
    { 0x0A7, CHECKSUMCFG_A7_SEED_MODE,  CHECKSUMCFG_A7_MASK_MODE,  CHECKSUMCFG_A7_ORDER,  CHECKSUMCFG_A7_EXTRA },
    { 0x0A8, CHECKSUMCFG_A8_SEED_MODE,  CHECKSUMCFG_A8_MASK_MODE,  CHECKSUMCFG_A8_ORDER,  CHECKSUMCFG_A8_EXTRA },
    { 0x0AD, CHECKSUMCFG_AD_SEED_MODE,  CHECKSUMCFG_AD_MASK_MODE,  CHECKSUMCFG_AD_ORDER,  CHECKSUMCFG_AD_EXTRA },
    { 0x0B1, CHECKSUMCFG_B1_SEED_MODE,  CHECKSUMCFG_B1_MASK_MODE,  CHECKSUMCFG_B1_ORDER,  CHECKSUMCFG_B1_EXTRA },
    { 0x0B2, CHECKSUMCFG_B2_SEED_MODE,  CHECKSUMCFG_B2_MASK_MODE,  CHECKSUMCFG_B2_ORDER,  CHECKSUMCFG_B2_EXTRA },
    { 0x0FD, CHECKSUMCFG_FD_SEED_MODE,  CHECKSUMCFG_FD_MASK_MODE,  CHECKSUMCFG_FD_ORDER,  CHECKSUMCFG_FD_EXTRA },
    { 0x101, CHECKSUMCFG_101_SEED_MODE, CHECKSUMCFG_101_MASK_MODE, CHECKSUMCFG_101_ORDER, CHECKSUMCFG_101_EXTRA },
    { 0x104, CHECKSUMCFG_104_SEED_MODE, CHECKSUMCFG_104_MASK_MODE, CHECKSUMCFG_104_ORDER, CHECKSUMCFG_104_EXTRA },
    { 0x106, CHECKSUMCFG_106_SEED_MODE, CHECKSUMCFG_106_MASK_MODE, CHECKSUMCFG_106_ORDER, CHECKSUMCFG_106_EXTRA },
    { 0x116, CHECKSUMCFG_116_SEED_MODE, CHECKSUMCFG_116_MASK_MODE, CHECKSUMCFG_116_ORDER, CHECKSUMCFG_116_EXTRA },
    { 0x117, CHECKSUMCFG_117_SEED_MODE, CHECKSUMCFG_117_MASK_MODE, CHECKSUMCFG_117_ORDER, CHECKSUMCFG_117_EXTRA },
    { 0x118, CHECKSUMCFG_118_SEED_MODE, CHECKSUMCFG_118_MASK_MODE, CHECKSUMCFG_118_ORDER, CHECKSUMCFG_118_EXTRA },
    { 0x11D, CHECKSUMCFG_11D_SEED_MODE, CHECKSUMCFG_11D_MASK_MODE, CHECKSUMCFG_11D_ORDER, CHECKSUMCFG_11D_EXTRA },
    { 0x11E, CHECKSUMCFG_11E_SEED_MODE, CHECKSUMCFG_11E_MASK_MODE, CHECKSUMCFG_11E_ORDER, CHECKSUMCFG_11E_EXTRA },
    { 0x120, CHECKSUMCFG_120_SEED_MODE, CHECKSUMCFG_120_MASK_MODE, CHECKSUMCFG_120_ORDER, CHECKSUMCFG_120_EXTRA },
    { 0x121, CHECKSUMCFG_121_SEED_MODE, CHECKSUMCFG_121_MASK_MODE, CHECKSUMCFG_121_ORDER, CHECKSUMCFG_121_EXTRA },
    { 0x126, CHECKSUMCFG_126_SEED_MODE, CHECKSUMCFG_126_MASK_MODE, CHECKSUMCFG_126_ORDER, CHECKSUMCFG_126_EXTRA },
    { 0x12E, CHECKSUMCFG_12E_SEED_MODE, CHECKSUMCFG_12E_MASK_MODE, CHECKSUMCFG_12E_ORDER, CHECKSUMCFG_12E_EXTRA },
    { 0x130, CHECKSUMCFG_130_SEED_MODE, CHECKSUMCFG_130_MASK_MODE, CHECKSUMCFG_130_ORDER, CHECKSUMCFG_130_EXTRA },
    { 0x134, CHECKSUMCFG_134_SEED_MODE, CHECKSUMCFG_134_MASK_MODE, CHECKSUMCFG_134_ORDER, CHECKSUMCFG_134_EXTRA },
    { 0x135, CHECKSUMCFG_135_SEED_MODE, CHECKSUMCFG_135_MASK_MODE, CHECKSUMCFG_135_ORDER, CHECKSUMCFG_135_EXTRA },
    { 0x18C, CHECKSUMCFG_18C_SEED_MODE, CHECKSUMCFG_18C_MASK_MODE, CHECKSUMCFG_18C_ORDER, CHECKSUMCFG_18C_EXTRA },
    { 0x1A2, CHECKSUMCFG_1A2_SEED_MODE, CHECKSUMCFG_1A2_MASK_MODE, CHECKSUMCFG_1A2_ORDER, CHECKSUMCFG_1A2_EXTRA },
    { 0x1AB, CHECKSUMCFG_1AB_SEED_MODE, CHECKSUMCFG_1AB_MASK_MODE, CHECKSUMCFG_1AB_ORDER, CHECKSUMCFG_1AB_EXTRA },
    { 0x2B7, CHECKSUMCFG_2B7_SEED_MODE, CHECKSUMCFG_2B7_MASK_MODE, CHECKSUMCFG_2B7_ORDER, CHECKSUMCFG_2B7_EXTRA },
    { 0x30B, CHECKSUMCFG_30B_SEED_MODE, CHECKSUMCFG_30B_MASK_MODE, CHECKSUMCFG_30B_ORDER, CHECKSUMCFG_30B_EXTRA },
    { 0x30D, CHECKSUMCFG_30D_SEED_MODE, CHECKSUMCFG_30D_MASK_MODE, CHECKSUMCFG_30D_ORDER, CHECKSUMCFG_30D_EXTRA },
    { 0x31B, CHECKSUMCFG_31B_SEED_MODE, CHECKSUMCFG_31B_MASK_MODE, CHECKSUMCFG_31B_ORDER, CHECKSUMCFG_31B_EXTRA },
    { 0x32A, CHECKSUMCFG_32A_SEED_MODE, CHECKSUMCFG_32A_MASK_MODE, CHECKSUMCFG_32A_ORDER, CHECKSUMCFG_32A_EXTRA },
    { 0x365, CHECKSUMCFG_365_SEED_MODE, CHECKSUMCFG_365_MASK_MODE, CHECKSUMCFG_365_ORDER, CHECKSUMCFG_365_EXTRA },
    { 0x366, CHECKSUMCFG_366_SEED_MODE, CHECKSUMCFG_366_MASK_MODE, CHECKSUMCFG_366_ORDER, CHECKSUMCFG_366_EXTRA },
    { 0x380, CHECKSUMCFG_380_SEED_MODE, CHECKSUMCFG_380_MASK_MODE, CHECKSUMCFG_380_ORDER, CHECKSUMCFG_380_EXTRA },
    { 0x381, CHECKSUMCFG_381_SEED_MODE, CHECKSUMCFG_381_MASK_MODE, CHECKSUMCFG_381_ORDER, CHECKSUMCFG_381_EXTRA },
    { 0x382, CHECKSUMCFG_382_SEED_MODE, CHECKSUMCFG_382_MASK_MODE, CHECKSUMCFG_382_ORDER, CHECKSUMCFG_382_EXTRA },
    { 0x385, CHECKSUMCFG_385_SEED_MODE, CHECKSUMCFG_385_MASK_MODE, CHECKSUMCFG_385_ORDER, CHECKSUMCFG_385_EXTRA },
    { 0x391, CHECKSUMCFG_391_SEED_MODE, CHECKSUMCFG_391_MASK_MODE, CHECKSUMCFG_391_ORDER, CHECKSUMCFG_391_EXTRA },
    { 0x392, CHECKSUMCFG_392_SEED_MODE, CHECKSUMCFG_392_MASK_MODE, CHECKSUMCFG_392_ORDER, CHECKSUMCFG_392_EXTRA },
    { 0x395, CHECKSUMCFG_395_SEED_MODE, CHECKSUMCFG_395_MASK_MODE, CHECKSUMCFG_395_ORDER, CHECKSUMCFG_395_EXTRA },
    { 0x3BE, CHECKSUMCFG_3BE_SEED_MODE, CHECKSUMCFG_3BE_MASK_MODE, CHECKSUMCFG_3BE_ORDER, CHECKSUMCFG_3BE_EXTRA },
    { 0x3C0, CHECKSUMCFG_3C0_SEED_MODE, CHECKSUMCFG_3C0_MASK_MODE, CHECKSUMCFG_3C0_ORDER, CHECKSUMCFG_3C0_EXTRA },
    { 0x3C8, CHECKSUMCFG_3C8_SEED_MODE, CHECKSUMCFG_3C8_MASK_MODE, CHECKSUMCFG_3C8_ORDER, CHECKSUMCFG_3C8_EXTRA },
    { 0x3DB, CHECKSUMCFG_3DB_SEED_MODE, CHECKSUMCFG_3DB_MASK_MODE, CHECKSUMCFG_3DB_ORDER, CHECKSUMCFG_3DB_EXTRA },
    { 0x3E5, CHECKSUMCFG_3E5_SEED_MODE, CHECKSUMCFG_3E5_MASK_MODE, CHECKSUMCFG_3E5_ORDER, CHECKSUMCFG_3E5_EXTRA },
    { 0x3E8, CHECKSUMCFG_3E8_SEED_MODE, CHECKSUMCFG_3E8_MASK_MODE, CHECKSUMCFG_3E8_ORDER, CHECKSUMCFG_3E8_EXTRA },
    { 0x3EC, CHECKSUMCFG_3EC_SEED_MODE, CHECKSUMCFG_3EC_MASK_MODE, CHECKSUMCFG_3EC_ORDER, CHECKSUMCFG_3EC_EXTRA },
    { 0x3FE, CHECKSUMCFG_3FE_SEED_MODE, CHECKSUMCFG_3FE_MASK_MODE, CHECKSUMCFG_3FE_ORDER, CHECKSUMCFG_3FE_EXTRA },
    { 0x497, CHECKSUMCFG_497_SEED_MODE, CHECKSUMCFG_497_MASK_MODE, CHECKSUMCFG_497_ORDER, CHECKSUMCFG_497_EXTRA },
    { 0x520, CHECKSUMCFG_520_SEED_MODE, CHECKSUMCFG_520_MASK_MODE, CHECKSUMCFG_520_ORDER, CHECKSUMCFG_520_EXTRA },
    { 0x54B, CHECKSUMCFG_54B_SEED_MODE, CHECKSUMCFG_54B_MASK_MODE, CHECKSUMCFG_54B_ORDER, CHECKSUMCFG_54B_EXTRA },
    { 0x584, CHECKSUMCFG_584_SEED_MODE, CHECKSUMCFG_584_MASK_MODE, CHECKSUMCFG_584_ORDER, CHECKSUMCFG_584_EXTRA },
    { 0x585, CHECKSUMCFG_585_SEED_MODE, CHECKSUMCFG_585_MASK_MODE, CHECKSUMCFG_585_ORDER, CHECKSUMCFG_585_EXTRA },
    { 0x5BE, CHECKSUMCFG_5BE_SEED_MODE, CHECKSUMCFG_5BE_MASK_MODE, CHECKSUMCFG_5BE_ORDER, CHECKSUMCFG_5BE_EXTRA },
    { 0x5F0, CHECKSUMCFG_5F0_SEED_MODE, CHECKSUMCFG_5F0_MASK_MODE, CHECKSUMCFG_5F0_ORDER, CHECKSUMCFG_5F0_EXTRA },
    { 0x640, CHECKSUMCFG_640_SEED_MODE, CHECKSUMCFG_640_MASK_MODE, CHECKSUMCFG_640_ORDER, CHECKSUMCFG_640_EXTRA },
    { 0x641, CHECKSUMCFG_641_SEED_MODE, CHECKSUMCFG_641_MASK_MODE, CHECKSUMCFG_641_ORDER, CHECKSUMCFG_641_EXTRA },
    { 0x64A, CHECKSUMCFG_64A_SEED_MODE, CHECKSUMCFG_64A_MASK_MODE, CHECKSUMCFG_64A_ORDER, CHECKSUMCFG_64A_EXTRA },
    { 0x65D, CHECKSUMCFG_65D_SEED_MODE, CHECKSUMCFG_65D_MASK_MODE, CHECKSUMCFG_65D_ORDER, CHECKSUMCFG_65D_EXTRA },
    { 0x65F, CHECKSUMCFG_65F_SEED_MODE, CHECKSUMCFG_65F_MASK_MODE, CHECKSUMCFG_65F_ORDER, CHECKSUMCFG_65F_EXTRA },
    { 0x668, CHECKSUMCFG_668_SEED_MODE, CHECKSUMCFG_668_MASK_MODE, CHECKSUMCFG_668_ORDER, CHECKSUMCFG_668_EXTRA },
    { 0x670, CHECKSUMCFG_670_SEED_MODE, CHECKSUMCFG_670_MASK_MODE, CHECKSUMCFG_670_ORDER, CHECKSUMCFG_670_EXTRA },
    { 0x6AE, CHECKSUMCFG_6AE_SEED_MODE, CHECKSUMCFG_6AE_MASK_MODE, CHECKSUMCFG_6AE_ORDER, CHECKSUMCFG_6AE_EXTRA },
    { 0x6B2, CHECKSUMCFG_6B2_SEED_MODE, CHECKSUMCFG_6B2_MASK_MODE, CHECKSUMCFG_6B2_ORDER, CHECKSUMCFG_6B2_EXTRA },
    { 0x6B4, CHECKSUMCFG_6B4_SEED_MODE, CHECKSUMCFG_6B4_MASK_MODE, CHECKSUMCFG_6B4_ORDER, CHECKSUMCFG_6B4_EXTRA },
    { 0x6B7, CHECKSUMCFG_6B7_SEED_MODE, CHECKSUMCFG_6B7_MASK_MODE, CHECKSUMCFG_6B7_ORDER, CHECKSUMCFG_6B7_EXTRA },
    { 0x6B8, CHECKSUMCFG_6B8_SEED_MODE, CHECKSUMCFG_6B8_MASK_MODE, CHECKSUMCFG_6B8_ORDER, CHECKSUMCFG_6B8_EXTRA },
};

// Total count
static const size_t PER_ID_CFG_TABLE_COUNT =
    sizeof(PER_ID_CFG_TABLE) / sizeof(PER_ID_CFG_TABLE[0]);
